### PR TITLE
Replace trollius by asyncio

### LINKED ISSUE #520: Potential trollius issue
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: Docker container running on: `Linux 2b5aca1a9b8b 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `python --version Python 2.7.12
python3 --version Python 3.5.2`
* Version of catkin_tools: 
```
catkin --version
catkin_tools 0.4.4 (C) 2014-2018 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```
* ROS Distro: `kinetic`

### Build / Run Issue
* [x] I did  not `read this`

### Expected Behavior
Output build status correctly to the terminal and cleanly exit

### Actual Behavior

```bash
root@dadc0fe3d78b:/home/ws# catkin build
-------------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/kinetic
Workspace:                   /home/ws
-------------------------------------------------------
Source Space:       [exists] /home/ws/src
Log Space:         [missing] /home/ws/logs
Build Space:        [exists] /home/ws/build
Devel Space:        [exists] /home/ws/devel
Install Space:     [missing] /home/ws/install
DESTDIR:            [unused] None
-------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        merged
-------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
-------------------------------------------------------
[build] Found '1' packages in 0.0 seconds.                                                                                                                                                                                                    
Starting  >>> catkin_tools_prebuild                                                                                                                                                                                                           
Finished  <<< catkin_tools_prebuild                [ 2.2 seconds ]                                                                                                                                                                            
Starting  >>> <Project_Name>                                                                                                                                                                                                                       
Finished  <<< <Project_Name>                        [ 3.3 seconds ]                                                                                                                                                                            
[build] Summary: All 2 packages succeeded!                                                                                                                                                                                                    
[build]   Ignored:   None.                                                                                                                                                                                                                    
[build]   Warnings:  None.                                                                                                                                                                                                                    
[build]   Abandoned: None.                                                                                                                                                                                                                    
[build]   Failed:    None.                                                                                                                                                                                                                    
[build] Runtime: 5.4 seconds total.                                                                                                                                                                                                           
[build] Note: Workspace packages have changed, please re-source setup files to use them.
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/trollius/base_events.py", line 395, in __del__
  File "/usr/local/lib/python3.5/dist-packages/trollius/unix_events.py", line 65, in close
  File "/usr/local/lib/python3.5/dist-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

This error output shows up after catkin build, catkin run_tests, and catkin test. It does NOT show up after catkin_make or catkin_test_results build.

### Steps to Reproduce the Issue

We are using a modified kinetic ros docker - added pip/catkin etc. 
Single simple package, few system deps, build, run tests. 

Any idea if this is a trollius issue directly or a python2/3 issue?

### LINKED ISSUE #558: python3-catkin-tools debian uninstallable on bionic due to missing python3-trollius package
I tried to install python3-catkin-tools today on a new bionic machine and it failed to install

```
$ sudo apt install python3-catkin-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-catkin-tools : Depends: python3-trollius but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I've fallen back to the python2 version for now to keep working. 

It appears that the python3-trollius package is only available on xenial and not newer: https://packages.ubuntu.com/xenial/python3-trollius

### PR DESCRIPTION
**Pull request by timonegk**
Since trollius is a python2 package that is not necessary for python3 because the functionality has been replaced by the python `asyncio` module, this pull request replaces trollius by asyncio. It closes #520 and would close #558 because the dependency to trollius could be dropped.
To be python3 compatible, #565 should also be merged.

Obviously, this pull request would drop python2 support, which is currently probably not realistic. Would it be possible to merge this to a separate branch to release a different version for python3?

### CODE REVIEW

**Comment by timonegk** [comment]
A version-agnostic implementation unfortunately does not seem to be possible because the new `from()` function is invalid syntax in python2. But there there might be a way of circumventing this function that I am not aware of.

**Comment by v4hn** [comment]
@mikepurvis How do you want to handle this version-incompatibility here then?
Any chance of having a separate python3 branch?

**Comment by mikepurvis** [comment]
Thanks for doing this work! Looks like the changes are pretty straight forward.

Per @wjwwood's comment on https://github.com/catkin/catkin_tools/issues/558#issuecomment-538165609, I'd be fine to just merge this and release it as 0.5.0, supporting Python 3.5+ and Ubuntu 16.04+ only. Trusty is five years old at this point, and ROS Indigo was EOL in April 2019.

At the end of the day, `catkin_tools` is a CLI utility, not a library, so short of weirdness with ROS workspace `PYTHONPATH` values, it really shouldn't really impact people that much to have the tool suddenly be running under Python 3 rather than 2 (and if the `PYTHONPATH` does turn out to be a problem, we could consider adding logic to the entry_point that sanitizes the `sys.path` before importing anything external).

**Comment by v4hn** [comment]
@mikepurvis Sounds wonderful!

Could you patch CI to remove the python2.7 checks then so CI succeeds here and this gets merged?

**Comment by mikepurvis** [comment]
You should be able to make the CI updates part of this change! Just update the travis config here:

https://github.com/catkin/catkin_tools/blob/master/.travis.yml

And `trollius` should be dropped as a dep from the `requirements.txt` and `setup.py` files as well.

**Comment by wolfv** [comment]
This would be great, as this would make catkin_tools work with newer Python releases in the `conda` package manager! I just realized after I published the package that trollius and asyncio are not exactly drop-in replaceable.

**Comment by wolfv** [comment]
I wonder if you could use `exec(...)` or eval(...) to work around the missing keyword problem.

**Comment by mikepurvis** [comment]
Given that the target OS will be 16.04+, it probably makes sense to have it testing against Python 3.5, but either way this is fine for now. Thanks for the contribution!

Going to merge and then myself and others can use it from source for a bit before recommending a new release.

**Pull request merged**
