### PR TITLE
escape whitespaces in `catkin config` printout

### PR DESCRIPTION
**Pull request by pseyfert**
In the `catkin config` printout, the cmake-args line changes from
```
Additional CMake Args:       -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS=-g -fno-omit-frame-pointer -O3 -DNDEBUG -DENABLE_TIMING=0
```
to
```
Additional CMake Args:       -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS=-g\ -fno-omit-frame-pointer\ -O3\ -DNDEBUG -DENABLE_TIMING=0
```
thereby the printout can be copy and pasted to `catkin config
--cmake-args` without changing the configuration. In the above example
the last element `-DENABLE_TIMING` is a cmake option and not a
gcc preprocessor definition. Before this patch, this is
indistinguishable from the printout.

I did not thoroughly check which of the other entries in the printout might have whitespaces that deserve escaping - cmake-args is the only one where it occurs to me.

### CODE REVIEW

**Comment by timonegk** [comment]
I think I would prefer to enclose the argument in quotes if it contains spaces, rather than using backslashes, as I think it looks more understandable. Would this work for you as well?

**Comment by pseyfert** [comment]
(shortening the above example)
Using quotes will work, too. And I agree this looks better. I think like
```
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-g -O3"
```
would be nicest to read, but right now I don't see how to get this done at the same complexity on the generation side (here I put quotes only if there actually is a whitespace occuring, and then I quote the part after `=`).

At the same complexity to generate while still grouping the cmake arguments and being valid copy&pastes would be
```
"-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" "-DCMAKE_CXX_FLAGS=-g -O3"
```
(here I put every cmake argument in quotes, needed or not)

**Comment by timonegk** [comment]
I would imagine something like this

```python
def quote(argument):
    if ' ' in argument:
        key, value = argument.split('=')
        return key + '="' + value + '"'
    return argument
```

**Comment by pseyfert** [comment]
indeed that works. i used `split("=", 1)` to make sure only the first = gets split off for arguments like `-DCMAKE_CXX_FLAGS=-DPREPROCESSOR_VARIABLE=VALUE`.

**Comment by timonegk** [comment]
Ah yes, that's better. You don't seem to have pushed it, though?

**Comment by pseyfert** [comment]
:see_no_evil: whoops. also added handling a few more edge cases (absence of `=`, first space before the first `=`). I don't have examples for those but i think it's important `catkin config` doesn't crash should somebody run into such a scenario.

**Comment by timonegk** [comment]
Very nice, thank you. Finally please add a comment to the function describing why we need it and then we're good to go.

**Pull request merged**
