### PR TITLE
config/build: adding whitelist/blacklist behavior

### PR DESCRIPTION
**Pull request by jbohren**
`catkin_make` supports "whitelisting" packages with the `CATKIN_WHITELIST_PACKAGES` CMake variable. This PR adds these capabilities to `catkin config` command like so:

*Set packages on the whitelist:*
```
catkin config --whitelist foo bar
```
*Set packages on the blacklist:*
```
catkin config --blacklist foo bar
```

Example in #149, requested by @aghazi

### CODE REVIEW

**Comment by jbohren** [comment]
@wjwwood What do you think of this pattern?

**Comment by wjwwood** [comment]
I'm fine with the approach, but I'm concerned about the visibility of this feature. For example, is the black and white listing expressed in the build summary? I'd have to try it out locally. I'm not going to have time to do that in the next few days. Maybe by the end of the week I can give a spin with some more detailed feedback.

**Comment by jbohren** [comment]
It is shown in the build summary.

**Comment by NikolausDemmel** [comment]
I imagine this to be very powerful in combination with profiles.

+1

**Comment by jbohren** [comment]
@wjwwood The whitelist / blacklist info is printed here: 
https://github.com/jbohren-forks/catkin_tools/blob/feature-blacklist-whitelist/catkin_tools/context.py#L368-369

It's documented here:
https://github.com/jbohren-forks/catkin_tools/commit/df4950796d7b7b0267d1d06da3fc0c3e1d1b12bf#diff-2a8cdb2fb21c1e017c507e90f960ccbbR146

**Comment by wjwwood** [comment]
@jbohren I was talking about the build summary created in this pull request: https://github.com/catkin/catkin_tools/pull/138

Where the build is summarized like this:

**Comment by jbohren** [comment]
@wjwwood Ahh that one. No, it's not shown there. Should be easy to add a `Blacklisted` tag though. If there are whitelisted packages, should all the non-whitelisted ones show up as `Not Whitelisted`?

**Comment by wjwwood** [comment]
Yeah, I don't know how that should look, I was just going to mess around with the output until something looked reasonable, but it will be a few days until I have time to do that.

**Comment by jbohren** [comment]
Better idea: in addition to `Build Summary:` and `Failed Packages:` we could have the following additional categories:

- `Blacklisted Packages`
- `Non-Whitelisted Packages`

### Non-empty blacklist:

Blacklist: `pkg_c`, `pkg_d`, `pkg_e`

```
Build Summary:
 Not Built  pkg_a
 Successful pkg_b
Blacklisted Packages:
 Not Built pkg_c
 Not Built pkg_d
 Not Built pkg_e
Failed Packages:
 Failed    pkg_f
```

### Non-empty whitelist:

Whitelist: `pkg_a`, `pkg_b`

```
Build Summary:
 Not Built  pkg_a
 Successful pkg_b
Non-Whitelisted Packages:
 Not Built pkg_c
 Not Built pkg_d
 Not Built pkg_e
Failed Packages:
 Failed    pkg_f
```

### Non-empty blacklist and whitelist:

Blacklist: `pkg_e`
Whitelist: `pkg_a`, `pkg_b`

```
Build Summary:
 Not Built  pkg_a
 Successful pkg_b
Non-Whitelisted Packages:
 Not Built pkg_c
 Not Built pkg_d
Blacklisted Packages:
 Not Built pkg_e
Failed Packages:
 Failed    pkg_f
```

**Comment by wjwwood** [comment]
That's basically what I was thinking.

**Comment by davetcoleman** [comment]
This is awesome, I will try to test soon

**Comment by jbohren** [comment]
@wjwwood Ok. They're now printed in the build summary.

**Comment by wjwwood** [comment]
Other than the comments, looks good to me.

**Comment by jbohren** [comment]
@wjwwood I think I addressed all of your comments.

**Comment by wjwwood** [comment]
Looks good to me.

**Comment by hgaiser** [comment]
I just pulled the master branch and tried to blacklist some packages but it seems completely ignored. The output `catkin config` does show they are blacklisted, but `catkin build` still tries to build them. In `catkin build` I also see it is noted they are blacklisted in the listing of the profile. I tried clearing all catkin_tools stuff, all build files, but it still occurs.

**Comment by hgaiser** [comment]
Ah, found the issue ... my package that I wanted to blacklist was in a folder called common, so catkin is checking if `'common/package_name'` is in the blacklist, and I had blacklisted just `'package_name'`.

**Comment by jbohren** [comment]
@hgaiser No, you were right first. Thanks for the report. It looks like the whitelist/blacklist was looking at the package path instead of the package name to filter. See #175 for a fix.

**Comment by hgaiser** [comment]
In addition, it would be nice to support at least adding of blacklist / whitelist packages. I'm compiling a workspace and I find some package I can't compile because of library dependencies, I would like to add that to the blacklist.

**Comment by jbohren** [comment]
> In addition, it would be nice to support at least adding of blacklist / whitelist packages to the current list.

Yeah, for both this and the other list-type configure options, it would be good to have a `catkin config --append` option.

**Comment by hgaiser** [comment]
I was thinking to make `--blacklist` or `--whitelist` append by default since there already is a `--clear-blacklist` and `--clear-whitelist`. That way you retain the same functionality as with a `--append` option but with one less option.

**Comment by jbohren** [comment]
@hgaiser Take a look at #179 we can discuss this over there.

**Pull request merged**
