### PR TITLE
bump cmake min ver to 2.8.12

### LINKED ISSUE #633: [CMake] Warnings on deprecated minimum cmake version
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `uname -a`
`Linux archard 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux`

* Python Version: `python --version`
`Python 3.8.6`

* Version of catkin_tools: `catkin --version` OR *Git revision*
```
catkin_tools 0.4.5 (C) 2014-2020 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
```
* ROS Distro: `echo $ROS_DISTRO`
`noetic`

* CMake: `cmake --version`
```
cmake version 3.19.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [x] I did  not `read this`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)
No cmake warnings

### Actual Behavior
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake

  Update the VERSION argument <min> value or use a ...<max> suffice to tell CMake that the project does not need compatibility with older versions.
```

[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

Whenever building any catkin package with CMake version (3.19.1) I receive the following deprecation warning.

```bash
catkin build
```

Seems like the solution is to bump up our minimum required cmake versions to 2.8.12:
https://github.com/catkin/catkin_tools/search?q=required%28VERSION&type=code

### PR DESCRIPTION
**Pull request by acxz**
resolves #633

### CODE REVIEW

**Comment by mikepurvis** [comment]
Looks reasonable. [CMake 2.8.12 came out in 2013](https://cmake.org/pipermail/cmake/2013-October/056020.html), so no one's getting burned by this.

**Comment by acxz** [comment]
not entirely sure why the CI is failing, tho

**Comment by mikepurvis** [comment]
Looks like it's the sphinx spelling plugin again, but not sure why that would be triggering only on Python 3.5 / Xenial:

```
$ sphinx-build -b spelling . build -t use_spelling
Running Sphinx v3.3.1
Exception occurred:
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/sphinxcontrib/spelling/__init__.py", line 11, in <module>
    from .builder import SpellingBuilder
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/sphinxcontrib/spelling/builder.py", line 80
    logger.info(f'Looking for custom word list in {word_list}')
```

**Comment by acxz** [comment]
@mikepurvis seems that the CI is failing across the board, it fails on #635 as well.

**Comment by mikepurvis** [comment]
@acxz Well, the reason used to be that Clearpath (my employer) was using Xenial + Py 3.5. But that is no longer the case, so I'm fine to see that dropped.

I'll merge this as-is, but would be delighted if you'd be willing to file a follow-up cleaning up the CI configuration.

**Comment by acxz** [comment]
Thx for the merge!

Yeah I can write a PR rq that removes the py3.5 + xenial case

**Pull request merged**
