### PR TITLE
Fixes linked build-run depend & logic cleanup

### LINKED ISSUE #132: catkin list --depends-on ignores packages with run-only dependancies
The summary says it all. I noticed this mostly because the [baxter_sdk package](https://github.com/RethinkRobotics/baxter/blob/master/baxter_sdk/package.xml) was not being listed as a package that depends on any of the other baxter packages.

To verify, create a new workspace by merging [this rosinstall file](https://raw.githubusercontent.com/RethinkRobotics/baxter/master/baxter_sdk.rosinstall), and then run  `catkin list --depends-on baxter_interface`. You won't see baxter_sdk on that list!

### PR DESCRIPTION
**Pull request by IanTheEngineer**
This PR resolves #132
- Changes depends_on variable to be a python set()
  This makes it clearer and easier to do logic operations
  on list contents
- Adds the logic required to fall into the dependancies
  if-statement if there is only a run dependancy
- Fixes bug where run dependancies were only listed if
  build dependancies also exist
- Minor error message color fix to be consistent with other
  catkin verbs

I have tested this on a few of my workspaces, in particular the one mentioned in #132, and run depends are listed, even if there are no build depends.

### CODE REVIEW

**Comment by wjwwood** [comment]
Oops, sorry, I stepped on this a bit. Let me revert.

**Comment by wjwwood** [comment]
Ok, let me review this.

**Comment by wjwwood** [comment]
Cool, looks good to me. Thanks!

**Comment by IanTheEngineer** [comment]
Thanks William!

**Pull request merged**
