### PR TITLE
Needs sudo to install

### PR DESCRIPTION
**Pull request by davetcoleman**
Otherwise I get the following errors:

    error: could not create '/usr/local/lib/python2.7/dist-packages/tests': Permission denied

and then 

    error: could not delete '/etc/bash_completion.d/catkin_tools-completion.bash': Permission denied

### CODE REVIEW

**Comment by wjwwood** [comment]
It only needs sudo on some machines and depending on how you install it (you wouldn't need it in a virtual env). I'd prefer that there is a notice encouraging uses to use sudo if they get permission problems, rather than suggesting people always use it.

**Comment by davetcoleman** [comment]
I'm using what most everyone is using: Ubuntu 14.04. But sure, I've updated the commit

**Comment by wjwwood** [comment]
Thanks. (I'll have to fix the CI in a separate PR, something in travis changed).

**Comment by wjwwood** [comment]
Also, if you're on Ubuntu you should use `sudo apt-get install python-catkin-tools`. If you're invoking the `setup.py` directly then you're either not on Ubuntu or you're installing a development version from source (in which case you should be using a virtualenv). For both cases, most of the time using `sudo` would not be correct and it might lead developers to think they need `sudo` even when they actually don't which is misleading.

**Comment by davetcoleman** [comment]
Correct, I was attempting to test @jbohren's https://github.com/catkin/catkin_tools/pull/196

> in which case you should be using a virtualenv

What kind of virutalenv are you referring to? Docker?

**Comment by wjwwood** [comment]
@davetcoleman just search for `virtualenv`.

**Pull request merged**
