### PR TITLE
Replace dependant with dependent

### LINKED ISSUE #330: Spelling: dependant vs dependent
The spelling `dependant` (with an `a`) is used in several command-line parameters and places within the code (first noticed in the [catkin clean docs](http://catkin-tools.readthedocs.org/en/latest/verbs/catkin_clean.html)). This is the British spelling, which looks weird to me, but it is also not consistent, since the US spelling is used as well on that same page.

### PR DESCRIPTION
**Pull request by scpeters**
Closes #330.
~~~
sed -i -e 's@dependant@dependent@' `grep -rlI dependant .`
~~~

I didn't check this at all, I just ran the sed script.

### CODE REVIEW

**Comment by wjwwood** [comment]
I think those changes look reasonable. Thanks @scpeters!

@jbohren I'll leave this to you to merge, that way you have a chance to chime in before.

**Comment by scpeters** [comment]
I missed one (b55fe8a) because I didn't append `g` to the search / replace `sed` command.

**Comment by jbohren** [comment]
> I missed one (b55fe8a) because I didn't append `g` to the search / replace `sed` command.

Yeah and `catkin clean` could definitely use more unit tests (which would have caught this).

Thanks for the sedding, @scpeters .

**Comment by scpeters** [comment]
no problem!

**Pull request merged**
