### PR TITLE
Fixing Bug with CMake argument parsing

### PR DESCRIPTION
**Pull request by abhinavkssk**
This fixes the bug caused by ignoring of the arguments passed to cmake args to be ignored

### CODE REVIEW

**Comment by jbohren** [comment]
Can you give an example of what was working before and is no longer working now? It appears this PR is breaking the unit tests.

**Comment by abhinavkssk** [comment]
Previously, when giving additional cmake args such as.. 
catkin config --cmake-args -DPYTHON_EXECUTABLE=/usr/bin/python2 -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so

and then if I ran 'catkin build' and If I set to verbose output I can see that the python packages being read are those corresponding to python 3 as opposed to python 2 because of those additional arguments,

But making that change, I no longer get the same error. I'm not entirely sure it's the correct correction, that seemed to be the only relevant change from the previous version when it was working fine as compared to the latest commit.

**Comment by jbohren** [comment]
@abhinavkssk Does this branch work for you: https://github.com/jbohren-forks/catkin_tools/tree/abhin-arg-fix

**Comment by abhinavkssk** [comment]
@jbohren Yeah,this build is working fine.

**Comment by jbohren** [comment]
@abhinavkssk It's still not clear to me why this is failing for you on the `master` version. See this passing test: https://github.com/catkin/catkin_tools/pull/183

Can you post _exactly_ the commands your running, and then post the output of `catkin config`?

**Comment by wjwwood** [comment]
@abhinavkssk Can you please redo your commit with proper author information, currently it just says "Your Name". I'm inclined to take a commit without something valid there, so you'll need to update your name and email in the `git` config, see: https://help.github.com/articles/setting-your-username-in-git/

I mention this here because @jbohren's follow up pr (#184) builds on your commit as well.

**Comment by abhinavkssk** [comment]
@jbohren here are the commands I've run beginning from catkin init
```
catkin init
```
```
Initializing catkin workspace in `/home/abe/ctkin_ws`.
-------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/hydro
Workspace:                   /home/abe/ctkin_ws
Source Space:       [exists] /home/abe/ctkin_ws/src
Build Space:        [exists] /home/abe/ctkin_ws/build
Devel Space:        [exists] /home/abe/ctkin_ws/devel
Install Space:     [missing] /home/abe/ctkin_ws/install
DESTDIR:                     None
-------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
-------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
-------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------

```
```
catkin config --cmake-args -DPYTHON_EXECUTABLE=/usr/bin/python2 -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so
```
```
--------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/hydro
Workspace:                   /home/abe/ctkin_ws
Source Space:       [exists] /home/abe/ctkin_ws/src
Build Space:        [exists] /home/abe/ctkin_ws/build
Devel Space:        [exists] /home/abe/ctkin_ws/devel
Install Space:     [missing] /home/abe/ctkin_ws/install
DESTDIR:                     None
--------------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
--------------------------------------------------------------------------------
Additional CMake Args:       -DPYTHON_EXECUTABLE=/usr/bin/python2 -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so
Additional Make Args:        None
Additional catkin Make Args: None
--------------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------------
```
Now , when i run ` catkin build ` the build would fail saying 

```
  File "/opt/ros/hydro/lib/python2.7/site-packages/genmsg/template_tools.py", line 75
    raise RuntimeError, "Template file %s not found in template dir %s" % (template_file_name, template_dir)
```
Which seem to me its trying to use python3 as opposed to using python2

**Comment by abhinavkssk** [comment]
@wjwwood Thanks for the info, I've updated my username details for the commit

**Comment by jbohren** [comment]
@abhinavkssk Thanks for the additional details. It's still not clear to me why this isn't working. Could you post all of the command line output after `catkin build` to a [gist](gist.github.com)?

**Comment by abhinavkssk** [comment]
Here's the gist link for output to `catkin build` https://gist.github.com/abhinavkssk/71ed85bfca7cf9df3081
and 
in case you might need it here's the gist link to `catkin build --verbose`
https://gist.github.com/abhinavkssk/f3dbb7f9e3438201366a

**Comment by jbohren** [comment]
@abhinavkssk Can you put the output from `catkin build --verbose --force-cmake` up on a gist?

**Comment by jbohren** [comment]
@abhinavkssk Also can you see if the latest version of this works for you: https://github.com/jbohren-forks/catkin_tools/tree/abhin-arg-fix

**Comment by jbohren** [comment]
This is superseded by #184

**Pull request closed without merging**
