### PR TITLE
WIP Add the ninja capability to catkin by calling catkin build --ninja

### PR DESCRIPTION
**Pull request by AlexisTM**
Add ninja capability by calling: `catkin build --ninja`.

### CODE REVIEW

**Comment by mikepurvis** [comment]
@AlexisTM What more is needed for this to be mergable?

**Comment by AlexisTM** [comment]
[Note: I forgot I actually created the PR]
This is definitely unstable right now (see CI) with problems such as: variables are not passed properly to gcc.
I will push the last local commit and see what I can do.

**Comment by AlexisTM** [comment]
The main missing point is Unit tests to ensure that it works as expected.

**Comment by AlexisTM** [comment]
Sadly, I have effectively no time to review this and create unit tests.

**Pull request closed without merging**
