### PR TITLE
Fix link on index

### PR DESCRIPTION
**Pull request by wjwwood**
I think this is a fix that's truer to the original intent, should replace: https://github.com/catkin/catkin_tools/pull/328

### CODE REVIEW

**Comment by scpeters** [comment]
is there a preview of the docs from CI?

**Comment by wjwwood** [comment]
@scpeters no, but we can generate them on demand.

**Comment by scpeters** [comment]
as long as it makes the link clickable I approve

**Comment by wjwwood** [comment]
I checked it locally.

**Pull request merged**
