### PR TITLE
catkin_build: print log if stderr is not empty (linux side only), see #1

### PR DESCRIPTION
**Pull request by xqms**
As discussed in #1, opening a pull request to make discussion easier. Not ready for merge! This is merely a testbed to see if stdout/stderr interleaving poses an issue.

If something got printed on stderr by a build command, the user will want
to know about it. So gather stderr separately from stdout and check if
it is non-empty when the command finishes.

### CODE REVIEW

**Comment by jbohren** [comment]
@wjwwood  @xqms I've been hacking on this sketch for a new asyncio-based executor (which can also be used for cleaning packages). Take a look and tell me what you think.

https://gist.github.com/jbohren/9cd689c08782d6ffbcdf

**Comment by jbohren** [comment]
@xqms I've now incorporated the `asyncio` stuff into #196 and it detects and displays stuff printed to `stderr`.

**Comment by jbohren** [comment]
@xqms I'm going to close this now that #249 is merged. Thanks for bringing attention to this feature! I wouldn't have gotten involved with it had you not initially prototyped it!

**Comment by xqms** [comment]
@jbohren Thank *you* for going all the way and implementing it properly ;-)

**Pull request closed without merging**
