### PR TITLE
testing: Adding tests (and ci configs) which fail on El Capitan (0.3.x)

### PR DESCRIPTION
**Pull request by jbohren**

### CODE REVIEW

**Comment by jbohren** [comment]
According to https://travis-ci.org/catkin/catkin_tools/builds/125156823 it looks like `build_env.sh` fails to handle paths with whitespace on el cap, as well.

**Comment by jbohren** [comment]
@wjwwood So I don't think #354 is a regression, based on the same error on el cap: https://travis-ci.org/catkin/catkin_tools/builds/125169012

What do you think?

**Comment by wjwwood** [comment]
I agree, I think this is SIP at work. I don't think it is a regression of the `0.4` version of `catkin_tools`.

**Comment by wjwwood** [comment]
I'm going to close this.

**Pull request closed without merging**
