### PR TITLE
drop utf-8 encoding to compute file hashes in symlink stage

### LINKED ISSUE #311: UnicodeDecodeError decode error during linking
I just got this error during linking the devel products (this is on `pre-0.4.0-clean-pkgs`):

```
Errors     << zeno_tracking_lib:symlink /home/den2pal/work/ros_ws/logs/zeno_tracking_lib/build.symlink.003.log                                                                                                                             
Stage `symlink` failed with arguments:
  package: {'package_format': 2, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [<catkin_pkg.package.Dependency object at 0x7f7a4522bb90>, <catkin_pkg.package.Dependency object at 0x7f7a4522bcb0>, <catkin_pkg.package.Dependency object at 0x7f7a4522bc50>, <catkin_pkg.package.Dependency object at 0x7f7a4522be90>, <catkin_pkg.package.Dependency object at 0x7f7a451eb050>, <catkin_pkg.package.Dependency object at 0x7f7a451eb0b0>, <catkin_pkg.package.Dependency object at 0x7f7a451eb110>, <catkin_pkg.package.Dependency object at 0x7f7a451eb170>, <catkin_pkg.package.Dependency object at 0x7f7a451eb1d0>, <catkin_pkg.package.Dependency object at 0x7f7a451eb230>, <catkin_pkg.package.Dependency object at 0x7f7a451eb290>], 'name': 'zeno_tracking_lib', 'filename': '/home/den2pal/work/ros_ws/src/pilot/TrackingLib/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [<catkin_pkg.package.Dependency object at 0x7f7a451eb2f0>, <catkin_pkg.package.Dependency object at 0x7f7a451eb350>, <catkin_pkg.package.Dependency object at 0x7f7a451eb3b0>, <catkin_pkg.package.Dependency object at 0x7f7a451eb410>, <catkin_pkg.package.Dependency object at 0x7f7a451eb470>, <catkin_pkg.package.Dependency object at 0x7f7a451eb4d0>, <catkin_pkg.package.Dependency object at 0x7f7a451eb530>, <catkin_pkg.package.Dependency object at 0x7f7a451eb590>, <catkin_pkg.package.Dependency object at 0x7f7a451eb5f0>, <catkin_pkg.package.Dependency object at 0x7f7a451eb650>, <catkin_pkg.package.Dependency object at 0x7f7a451eb6b0>], 'doc_depends': [], 'test_depends': [], 'maintainers': [<catkin_pkg.package.Person object at 0x7f7a45220150>], 'version': '0.0.0', 'build_depends': [<catkin_pkg.package.Dependency object at 0x7f7a451eb710>, <catkin_pkg.package.Dependency object at 0x7f7a451eb770>, <catkin_pkg.package.Dependency object at 0x7f7a451eb7d0>, <catkin_pkg.package.Dependency object at 0x7f7a451eb830>, <catkin_pkg.package.Dependency object at 0x7f7a451eb890>, <catkin_pkg.package.Dependency object at 0x7f7a451eb8f0>, <catkin_pkg.package.Dependency object at 0x7f7a451eb950>, <catkin_pkg.package.Dependency object at 0x7f7a451eb9b0>, <catkin_pkg.package.Dependency object at 0x7f7a451eba10>, <catkin_pkg.package.Dependency object at 0x7f7a451eba70>, <catkin_pkg.package.Dependency object at 0x7f7a451ebad0>], 'urls': [], 'authors': [<catkin_pkg.package.Person object at 0x7f7a45220490>], 'licenses': ['ZenoWay internal'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0x7f7a451ebb30>], 'conflicts': [], 'description': u'Zeno Pilot TrackingLib'}
  metadata_path: /home/den2pal/work/ros_ws/.catkin_tools/profiles/default
  devel_manifest_path: /home/den2pal/work/ros_ws/.catkin_tools/profiles/default/packages/zeno_tracking_lib
  prebuild: False
  package_path: pilot/TrackingLib
  dest_devel_path: /home/den2pal/work/ros_ws/devel
  source_devel_path: /home/den2pal/work/ros_ws/devel/.private/zeno_tracking_lib
Traceback (most recent call last):
  File "/home/den2pal/work/py/catkin_tools/catkin_tools/execution/executor.py", line 148, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 40: ordinal not in range(128)
```

It seems that I had a strange character in a library name. After deleting the .so file manually and retyping the library name in `CMakeLists.txt` the problem is gone and I cannot reproduce it.

### PR DESCRIPTION
**Pull request by rhaschke**
This fixes #311 (UnicodeDecodeErrors) as pointed out in https://github.com/catkin/catkin_tools/issues/311#issuecomment-224572400. Relates to #368.

### CODE REVIEW

**Comment by wjwwood** [comment]
@rhaschke there are CI failures for this. I've merged #368, but I don't have push permission on this branch so I cannot rebase it (I'm assuming rebasing would address the issue). Can you rebase this or otherwise fix these failures (assuming they're related to the changes). Thanks.

**Comment by rhaschke** [comment]
@wjwwood: I rebased. However, Travis already fails on master. I fixed this in #428.

**Comment by rhaschke** [comment]
@wjwwood: I finally digged into this and found the underlying issue: 
@jbohren's idea was to compute the md5 hashes of files to compare them. However, opening files, opens them in text-mode by default, returning string objects when calling `read()`, which is not compatible to `digest()` that expects a byte array. Recoding sometimes failed on binary files. My first fix only removed the recoding to utf8. However it's also import to read the file in binary mode in the first place.
Travis passes now. This resolves #433 too (which is a rebase of #399).

**Comment by mikepurvis** [comment]
Nice!

**Comment by wjwwood** [comment]
Awesome, thanks @rhaschke.

**Comment by furushchev** [comment]
Hi, is there any plan to release new version including this patch?

**Comment by wjwwood** [comment]
> Hi, is there any plan to release new version including this patch?

Yes, I'm just swamped. But I'm going over the open pr's and issues now, so I think a new release is incoming. Sorry for the long drought of updates.

**Comment by nckswt** [comment]
Any update on the release of 0.4.5? Getting this fix would help out a lot!

**Comment by HareshMiriyala** [comment]
sudo apt-get install python-catkin fixed this issue for me.

**Comment by HareshMiriyala** [comment]
sudo apt-get install python-catkin-tools    fixed things for me !

**Pull request merged**
