### PR TITLE
Add option to clean pyc files

### PR DESCRIPTION
**Pull request by paulbovbel**
Stale .pyc files in the workspace have led to several strange issues seen during development.

Adding (default on) option to clean out .pyc files from the .src directory whenever the workspace is cleaned.

https://github.com/paulbovbel/catkin_tools/pull/1

### CODE REVIEW

**Comment by paulbovbel** [comment]
Ping, any interest in this?

**Comment by wjwwood** [comment]
I'm hesitant about this because it is Python specific and because it deletes files in the source space (which is a cardinal sin in my book). It might be ok in this case, but I'm not completely convinced. The `pyc` files should only be an issue if you delete the equivalent `py` file but not the `pyc` file. I think you need to provide more evidence as to why you think it necessary to remove these files automatically. I think you might find that these are not the root of the problem.

**Comment by mikepurvis** [comment]
A potential alternative is to [prevent them ever being created](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE).

**Comment by paulbovbel** [comment]
Fair enough, I'm on board with keeping the src space inviolate

**Comment by evenator** [comment]
Would it make sense to set `PYTHONDONTWRITEBYTECODE` in devel space setup scripts? Or is that too much spooky action at a distance?

**Pull request closed without merging**
