### PR TITLE
rebase of issue 399

### PR DESCRIPTION
**Pull request by wjwwood**
See #399

### CODE REVIEW

**Comment by wjwwood** [comment]
@rhaschke this is still failing in Python 3 even after I rebased it (again since merging #428) and the master branch is passing: https://github.com/catkin/catkin_tools/pull/434

At first glance I'm not sure what the issue is.

**Comment by mkoval** [comment]
I can confirm that this fixed #311 on an Ubuntu 14.04 machine using Python 2. Unfortunately, I have no idea what the original source of this error was or why the tests are currently failing on Python 3.

**Comment by arpit15** [comment]
This commit solved #311 for me on Ubuntu 14.04 with Python 2.

**Comment by wjwwood** [comment]
Closing due to https://github.com/catkin/catkin_tools/pull/399#issuecomment-292482789

**Pull request closed without merging**
