### PR TITLE
completion: adding bash (zsh) completion

### LINKED ISSUE #15: Add bash/zsh tab completion

### PR DESCRIPTION
**Pull request by jbohren**
**NOTE: Depends on #190 See [cli-completion-full](https://github.com/jbohren-forks/catkin_tools/tree/cli-completion-full) for the integrated branch**

Completes:

- `catkin [--CATKIN-OPTS...] <tab>` completes to all builtin verbs
- `catkin [--CATKIN-OPTS...] build [--BUILD-OPTS...] <tab>` completes to package names given by `catkin list`
- `catkin [--CATKIN-OPTS...] build [--BUILD-OPTS...] -<tab>` completes to `--dry-run --this --no-deps --continue-on-failure --force-cmake --verbose --summarize --no-notify`
- `catkin create <tab>` completes to `catkin create` sub-commands
- `catkin create pkg <tab>` completes to `catkin create pkg` optional arguments
- `catkin profile <tab>` completes to `catkin profile` sub-commands
- `catkin profile [set rename remove] <tab>` completes to existing profiles

***Note:*** If you want to use them in zsh, you still need to source the bash file.

Fixes #15

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
Cool! I looking forward to the feature.

Basic usage works fine, but e.g. the following breaks:

    catkin build --no-deps[TAB]

with error:

    bash: compgen: --: invalid option
    compgen: usage: compgen [-abcdefgjksuv] [-o option]  [-A action] [-G globpat] [-W wordlist]  [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [word]

similar for something like:

    catkin --h[TAB]

P.S.: Is `sudo python setup.py develop` supposed to install the `catkin-completion.bash` file? It does not seem to do that over here.

**Comment by jbohren** [comment]
> Basic usage works fine, but e.g. the following breaks:

Yeah, bash completion hacking is new for me, this is resolved in #f33e174

> P.S.: Is `sudo python setup.py develop` supposed to install the `catkin-completion.bash` file? It does not seem to do that over here.

No, I tried and it doesn't appear to install it, which makes sense since it's an external config file. For developing you can either add the following to your shell:

```
source /path/to/catkin_tools/completion/catkin-completion.bash
```

Alternatively you can link it to `/etc/bash_completion.d`:

```
cd /etc/bash_completion.d sudo ln -s /path/to/catkin_tools/completion/catkin-completion.bash
```

Note that if you want to use them in zsh, you still need to source the bash file.

**Comment by NikolausDemmel** [comment]
Phantastic. It even completes the build optional arguments :+1:

**Comment by adeguet1** [comment]
Can't wait to use it.

**Comment by wjwwood** [comment]
I think that the installation code should be more sophisticated, I actually had already done that part:

https://github.com/catkin/catkin_tools/commit/49165cf555f0566da02a1ccda987fbaecf2885b8

Can you take a look at that commit and consider using all or part of it?

**Comment by jbohren** [comment]
> I think that the installation code should be more sophisticated, I actually had already done that part:

Oh cool. Yeah I'll just update that with the added file.

**Comment by wjwwood** [comment]
Ok, just make sure to try it out, I only tested that strategy a bit.

**Comment by wjwwood** [comment]
Reviewing this I have a few questions:

- What's this file for? `catkin_tools-completion.sh`
- Have you tested installing this in a few different scenarios? Looking at my logic in the `setup.py` and poking at the value of `sys.prefix`, I'm not sure they're going to the right place.
- Should there be a `.zsh` which just sources the `.bash`? Even if the `.bash` has logic for when it is sourced by `.zsh` it seems like there should be a `.zsh` file.

**Comment by jbohren** [comment]
> - What's this file for? catkin_tools-completion.sh

Left over from your 0c97f5f. I got rid of it.

> - Have you tested installing this in a few different scenarios? Looking at my logic in the setup.py and poking at the value of sys.prefix, I'm not sure they're going to the right place.

No I haven't tested the installation. I don't know if I have time to.

> - Should there be a .zsh which just sources the .bash? Even if the .bash has logic for when it is sourced by .zsh it seems like there should be a .zsh file.

I don't think that's really necessary. I'm not sure where it would go, anyway.

**Comment by jbohren** [comment]
@wjwwood Separated the optimizations out into #190

**Comment by jbohren** [comment]
See [cli-completion-full](https://github.com/jbohren-forks/catkin_tools/tree/cli-completion-full) for the integrated branch.

**Comment by wjwwood** [comment]
Ok, I finally got around to testing this and fixing up my install logic on both Linux and OS X, in a variety of scenarios. I merged this manually after a rebase and adding this commit: f797eb6

**Comment by jbohren** [comment]
> Ok, I finally got around to testing this and fixing up my install logic on both Linux and OS X, in a variety of scenarios. I merged this manually after a rebase and adding this commit: f797eb6

Cool!

**Pull request closed without merging**
