### PR TITLE
build: fixing catkin make corruption error display

### LINKED ISSUE #150: KeyError: 'rf' on workspace with catkin_make artifacts
I get the following error:

    $ catkin build
    [build] Runtime: 0.0 seconds 
    Traceback (most recent call last):
      File "/usr/local/bin/catkin", line 9, in <module>
        load_entry_point('catkin-tools==0.2.1', 'console_scripts', 'catkin')()
      File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.1-py2.7.egg/catkin_tools/commands/catkin.py", line 198, in main
        sys.exit(args.main(args) or 0)
      File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.1-py2.7.egg/catkin_tools/verbs/catkin_build/cli.py", line 270, in main
        summarize_build=opts.summarize  # Can be True, False, or None
      File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.1-py2.7.egg/catkin_tools/verbs/catkin_build/build.py", line 488, in build_isolated_workspace
        "or clean the build space.".format(context.build_space_abs)))
    KeyError: 'rf'

The workspace was previously built with `catkin_make` and contains the old build and devel folders:

    $ ls -a 
    .  ..  build  .catkin_tools  .catkin_workspace  devel  src

After `rm -rf build devel`, it works. Tested both on the current .deb version (0.2.1-1) and latest `master` branch (0afc6f9c). I'm using ROS Hydro on Ubuntu 12.04.

### PR DESCRIPTION
**Pull request by jbohren**
Fixes #150

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by jbohren** [comment]
@wjwwood Since this is a bug that I think a lot of first-time users will run into, do you know when this will get out to pip / debs?

**Comment by wjwwood** [comment]
It will be at least Monday, I need my work desktop.

**Comment by tfoote** [comment]
@wjwwood we should do this after merging: https://github.com/ros-infrastructure/reprepro-updater/pull/17 https://github.com/ros-infrastructure/buildfarm_deployment_config/pull/4 and https://github.com/ros-infrastructure/ros_release_python/pull/10

**Comment by jbohren** [comment]
Any luck re: release?

**Comment by wjwwood** [comment]
I'm waiting on @tfoote to merge the above changes to our repos setup and test them. Maybe tomorrow.

**Comment by wjwwood** [comment]
@tfoote let me know when I can safely release, and I'll do it while were both at the office in case something happens.

**Comment by tfoote** [comment]
@wjwwood I merged them before leaving. Make sure to pull the latest of ros_release_python.

**Comment by jbohren** [comment]
Launch Keys

**Comment by wjwwood** [comment]
`0.2.2` released. @tfoote I did the "push_ros" script to push to the public mirrors, but it's not in the repos.ros.org pool yet, is there a new step?

I can install it with `pip`.

Rocket Good

**Comment by jbohren** [comment]
@wjwwood Well played.

**Comment by tfoote** [comment]
@wjwwood You need to run import_upstream.bash on the old farm: https://github.com/ros-infrastructure/reprepro-updater/blob/master/import_upstream.bash before syncing to public

on the new farm it's in this job: http://54.183.26.131:8080/job/import_upstream/

I've run import_upstream and push_ros it should be there as soon as they mirrors finish syncronizing.

**Pull request merged**
