### PR TITLE
[PR196 0/3] Cleanup of integrated test harness, other small fixes

### PR DESCRIPTION
**Pull request by jbohren**
This PR is a prerequisite to merging PR #196. The main changes in this PR include unifying the integrated test harnesses and adding numerous test cases. This PR also involves a few small additions, bugfixes, and cleanup. This PR is a prerequisite to the first segment of PR#196 (new execution pipeline).

The individual changes to the different components of `catkin_tools` are broken up into six atomic commits. Note that commit 8e2df65 only appears to be large due to re-indenting into a try-catch block. In the future, `catkin_tools/commands/catkin.py` could use some additional cleanup and refactoring.

### CODE REVIEW

**Comment by jbohren** [comment]
@wjwwood Here are some pre-req changes before merging in the new execution pipeline. Note that the added tests will fail due to a limitation of the current job server. We could fix the bug, but that job server is being replaced almost completely by the new implementation in a forthcoming PR.

**Comment by wjwwood** [comment]
These changes look ok, I opened a pr against your branch with some things I noticed while reviewing.

There are several other functions which are probably too complicated at this point and should be refactored, but we can tackle them later.

Once we iterate on and merge my pr against your branch I think this will be ready for merge. In the future go ahead and push your pr branches to the main repository, that way I can just add commits to pr's.

**Comment by jbohren** [comment]
This has been superseded by #248.

**Comment by jbohren** [comment]
Ignore last comment, closed wrong PR.

**Comment by jbohren** [comment]
@wjwwood Feel free to merge this if it looks good.

**Pull request merged**
