### PR TITLE
Fix for python3.9

### PR DESCRIPTION
**Pull request by ckurtz22**
(This breaks support for Python 3.4, if 3.4 was even supported)

Functionality for asyncio locks was changed and the current usage was deprecated, and finally removed in 3.9.
My changes are functional, as in catkin build works for me, but I'm not certain if I implemented all of the changes correctly so someone should double check my changes.

### CODE REVIEW

**Comment by ckurtz22** [comment]
Partially fixes #594

**Comment by nim65s** [comment]
Thanks, this fixed #636 for me !

**Comment by mikepurvis** [comment]
Merging as the failed 3.5 test is no longer present.

**Comment by mikepurvis** [comment]
Looks like the remaining failure here is related to Python 2, possible due it not being installed on Focal any more by default?

{code}
======================================================================

FAIL: tests.system.verbs.catkin_build.test_pythonpath.test_python2_devel

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.9.0/lib/python3.9/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/home/travis/build/catkin/catkin_tools/tests/system/verbs/catkin_build/test_pythonpath.py", line 32, in test_python2_devel

    assert re.match('^' + wf.workspace + '/devel/lib/python2\.\d/(site|dist)-packages$', ws_pythonpath)

AssertionError

======================================================================

FAIL: tests.system.verbs.catkin_build.test_pythonpath.test_python2_install

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.9.0/lib/python3.9/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/home/travis/build/catkin/catkin_tools/tests/system/verbs/catkin_build/test_pythonpath.py", line 65, in test_python2_install

    assert re.match('^' + wf.workspace + '/install/lib/python2\.\d/(site|dist)-packages$', ws_pythonpath)

AssertionError

----------------------------------------------------------------------
{code}

**Comment by mikepurvis** [comment]
But ddb06da7e0d1bb902e64b9262d52d339dda0a7c0 doesn't fix it because the `python2` package doesn't exit on Bionic and Xenial, so there needs to be an actual branch based on which distro it is.

**Pull request merged**
