### PR TITLE
testing: Adding tests (and ci configs) which fail on El Capitan (0.4.x)

### PR DESCRIPTION
**Pull request by jbohren**

### CODE REVIEW

**Comment by wjwwood** [comment]
Needs a rebase now? (there seem to be commits from the one I just merged #353)

**Comment by jbohren** [comment]
Yeah I'll rebase this. Also we can hold off on merging it until we figure out what the fix is.

**Comment by jbohren** [comment]
@wjwwood So I added two commits which make `ctest` work with plain CMake packages on El Capitan with SIP.

First, a491706 simply enables `CMAKE_MACOSX_RPATH` by default. This fixes running `ctest` in a linked develspace.

Second, 9c8b3be adds a Catkin package to the merged develspace test, which is apparently necessary to set up the environment. This means that there's something that the Catkin setup files are doing that the vanilla CMake ones aren't.

**Comment by wjwwood** [comment]
Just catching up on this issue, I do not think we can set `CMAKE_MACOSX_RPATH` by default in catkin tools because I think it is a choice that the developer and/or the packages being built should make. So we'll either have to decline this whole pr, or find a way to run these tests without SIP interfering. On my machines I just ended up disabling SIP, as it was just too painful to deal with.

**Comment by mikepurvis** [comment]
Closing due to inactivity.

**Pull request closed without merging**
