### PR TITLE
io: Handling ASCII stdout more gracefully.

### PR DESCRIPTION
**Pull request by jbohren**
@xqms Can you try running this branch in jenkins to better deal with the ASCII stdout?

This was the problem, as reported in https://github.com/catkin/catkin_tools/pull/249#issuecomment-164719546
> ```
Warnings << gazebo_ros_control:make /var/lib/jenkins/jobs/spacebot/workspace/build/_logs/gazebo_ros_control/build.make.000.log
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/max/install/catkin_tools/catkin_tools/execution/controllers.py", line 452, in run
    wide_log('\n'.join(lines))
  File "/home/max/install/catkin_tools/catkin_tools/common.py", line 450, in wide_log
    wide_log_fn(msg, **kwargs)
  File "/home/max/install/catkin_tools/catkin_tools/common.py", line 419, in disabled_wide_log
    log(msg, **kwargs)
  File "/home/max/install/catkin_tools/catkin_tools/common.py", line 272, in log
    print(*args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 129: ordinal not in range(128)
```

> The unicode character 2018 is "LEFT SINGLE QUOTATION MARK", emitted by gcc on my system:
> ```
[...] warning: enumeration value ‘EFFORT’ not handled in switch
```

### CODE REVIEW

**Comment by xqms** [comment]
Works for me under jenkins. The question is if this is any better than setting the output encoding to UTF-8

```
sys.setdefaultencoding('utf-8')
```

or always using `str.encode('utf-8')`...

**Comment by jbohren** [comment]
> Works for me under jenkins. The question is if this is any better than setting the output encoding to UTF-8

I'm wondering if there are any scenarios where stdout needs to be ASCII, and if in those scenarios, you get a similar exception. As opposed to just bring set to ASCII while still supporting utf-8.

**Comment by xqms** [comment]
> I'm wondering if there are any scenarios where stdout needs to be ASCII

If so, what would be our strategy in that case? Drop all non-ASCII characters?
I'd argue encoding to UTF-8 is a better alternative.

> As opposed to just bring set to ASCII while still supporting utf-8.

Not sure what that is supposed to mean ;-)

**Comment by jbohren** [comment]
>> I'm wondering if there are any scenarios where stdout needs to be ASCII
> If so, what would be our strategy in that case? Drop all non-ASCII characters?
I'd argue encoding to UTF-8 is a better alternative.

Yeah, I think that's fine, as well. It might make sense to set a global flag the first time it happens, though, and print pre-encoded data, 

>>As opposed to just bring set to ASCII while still supporting utf-8.
>Not sure what that is supposed to mean ;-)

*typo: being set to ASCII

From what I understand, Python's understanding of the stdout encoding might not be correct.

**Comment by jbohren** [comment]
Merged via a2cfdf7

**Pull request closed without merging**
