### PR TITLE
changelogs

### PR DESCRIPTION
**Pull request by wjwwood**
@jbohren can you have a look at the changelogs and see if I missed anything worth mentioning (there was a lot of stuff and I tried to prune it down some).

### CODE REVIEW

**Comment by jbohren** [comment]
Is it ok if I just edit this branch in-place?

**Comment by wjwwood** [comment]
Sure, just push new commits and I'll squash on merge.

**Comment by jbohren** [comment]
Ok, I added some things that I thought were worth mentioning.

**Comment by wjwwood** [comment]
Thanks, I'll squash and merge.

**Pull request merged**
