### PR TITLE
Enhance: add completion for zsh and fix install location

### PR DESCRIPTION
**Pull request by wkentaro**
also fix install location for completion files.

By installing `_catkin` file, zsh users don't have to source `catkin_tools-completion.bash` file.

### CODE REVIEW

**Comment by wkentaro** [comment]
this also fix: https://github.com/catkin/catkin_tools/issues/222

**Comment by wjwwood** [comment]
I think the same issues applies to this pr as I commented on `wstool`:

https://github.com/vcstools/wstool/pull/39#issuecomment-127072241

**Comment by wkentaro** [comment]
I updated the install location with https://github.com/vcstools/wstool/pull/39 .

**Comment by wkentaro** [comment]
ping

**Comment by wkentaro** [comment]
ping

**Comment by NikolausDemmel** [comment]
+1

**Comment by wjwwood** [comment]
I merged this manually.

**Comment by wkentaro** [comment]
Thanks.

**Pull request closed without merging**
